name: prBuild

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo message
        run: echo "Deploy pr resources to staging"

      - name: PR Comment
        uses: ./.github/actions/comment
        env:
          BUILD_LOGS_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          type: pr
          token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            | Name | Value |
            | --- | --- |
            | Build Logs | ${{ env.BUILD_LOGS_URL }} |

# install deps

# build pr resources

# deploy pr resources
