name: prBuild

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo message
        run: |
          echo "Deploy pr resources to staging"
          # echo ::set-output name=buildOutput::""

      - name: Comment on PR
        uses: actions/github-script@v3
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '| Name | Value |\n| --- | --- |\n| Build Logs | https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} |',
            })

      # - name: PR Comment
      #   uses: ./.github/actions/comment
      #   env:
      #     BUILD_LOGS_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      #   with:
      #     type: pr
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     message: |
            # | Name | Value |
            # | --- | --- |
            # | Build Logs | ${{ env.BUILD_LOGS_URL }} |

# install deps

# build pr resources

# deploy pr resources
