name: prCleanup

on:
  pull_request:
    types: [closed]

jobs:
  Cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo message
        run: echo "Remove created aws resources for the pr"

      - name: Comment on PR
        uses: actions/github-script@v3
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Successfully cleaned-up pr AWS resources!',
            })

# install deps

# remove resources with pr number
