name: rollbackDeployment

on:
  issues:
    types: [labeled]
  issue_comment:
    types: [created]

jobs:
  StagingPreviousDeployments:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'RollbackStaging'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Echo message - Fetch previous staging deployments
        run: echo "Build and deploy to prod after approval"

      - name: Comment on Issue
        uses: actions/github-script@v5
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Previous `staging` deployments:',
            })

  RollbackStaging:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request && contains(github.event.comment.body, '/rollback')}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Get rollback timestamp
        uses: actions/github-script@v5
        id: rollback-timestamp
        result-encoding: string
        with:
          script: |
            const commentBody = context.payload.comment.body;
            const rollbackTimestamp = commentBody.split('/rollback ')[1];

            if (rollbackTimestamp.indexOf(' ') >= 0) { # whitespaces available
              github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `Invalid rollback parameter input: ${commentBody}`,
              });

              github.reactions.createForIssueComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: context.payload.comment.id,
                content: "eyes",
              });
            } else {
              github.reactions.createForIssueComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: context.payload.comment.id,
                content: "+1",
              });

              return rollbackTimestamp;
            }

      - name: Comment on Issue
        uses: actions/github-script@v5
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Successfully rolled-back previous `staging` deployment with timestamp `${{steps.rollback-timestamp.outputs.result}}`',
            })

# comment deployment lists available

# get user input

# if prod, wait approval
