name: rollbackDeployment

on:
  issues:
    types: [opened, labeled]

jobs:
  Rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: View context attributes
        uses: actions/github-script@v5
        with:
          script: console.log(context)

      - name: Comment on Issue - Created
        uses: actions/github-script@v3
        if: issues.types != 'labeled'
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Please label the issue with an appropriate rollback tag. For example, the tags `RollbackStaging` or `RollbackProd`',
            })

      - name: Comment on Issue - Labeled
        uses: actions/github-script@v3
        if: issues.types == 'labeled'
        with:
          script: |
            let rollbackStage = context.label.name;
            rollbackStage = rollbackStage.toLowerCase().split('rollback')[1];

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Preparing to rollback previous deployment for STAGE='${rollbackStage}'`,
            })

# comment deployment lists available

# get user input

# if prod, wait approval
