name: rollbackDeployment

on:
  issues:
    types: [opened, labeled]

jobs:
  Rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: View context attributes
        uses: actions/github-script@v5
        with:
          script: console.log(context)

      - name: Comment on Issue
        uses: actions/github-script@v3
        with:
          script: |
            let commentBody = 'Please label the issue with an appropriate rollback tag. For example, the tags `RollbackStaging` or `RollbackProd`';;

            if (context.label && context.label.name) {
              let rollbackStage = context.label.name;
              rollbackStage = rollbackStage.toLowerCase().split('rollback')[1];
              commentBody = `Preparing to rollback previous deployment for STAGE='${rollbackStage}'`;
            }

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody,
            })

# comment deployment lists available

# get user input

# if prod, wait approval
