name: rollbackDeployment

on:
  issues:
    types: [opened, labeled]

jobs:
  Rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: View context attributes
        uses: actions/github-script@v5
        with:
          script: console.log(context)

      - name: Comment on Issue
        uses: actions/github-script@v3
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Please label the issue with an appropriate rollback tag. For example, the tags _RollbackStaging_ or _RollbackProd_',
            })

      - name: Echo message
        run: echo "Comment on next available actions from user."

# comment deployment lists available

# get user input

# if prod, wait approval
