name: stagingBuild

on:
  push:
    branches: [main, master]

env:
  AWS_REGION: us-east-1
  NODE_VERSION: '14'

jobs:
  BuildDeployStaging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org

      - name: Restore & cache dependencies
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm i --no-package-lock

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to Staging env
        run: SLS_DEBUG=* && $(npm bin)/sls deploy -s staging

      # - name: Echo message
      #   run: echo "Build and deploy to staging, await prod approval"


  BuildDeployProd:
    runs-on: ubuntu-latest
    needs: BuildDeployStaging
    environment: 'prod'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org

      - name: Restore & cache dependencies
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm i --no-package-lock

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to Staging env
        run: SLS_DEBUG=* && $(npm bin)/sls deploy -s prod

      # - name: Echo message
      #   run: echo "Build and deploy to prod after approval"
