name: stagingBuild

on:
  push:
    branches: [main, master]

jobs:
  BuildDeployStaging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo message
        run: echo "Build and deploy to staging, await prod approval"


  BuildDeployProd:
    runs-on: ubuntu-latest
    needs: BuildDeployStaging
    environment: 'prod'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo message
        run: echo "Build and deploy to prod after approval"
